apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-tp3-deployment
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: louaykharouf/webapp-tp3

