apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp-tp3-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: docker.io/library/webapp-tp3
